# Generated by Django 3.0 on 2025-08-29 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20250823_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='notifications',
            new_name='title',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
