# Generated by Django 3.0 on 2025-11-11 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_buy_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_stock',
            name='FAVOURITE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.favourite'),
        ),
    ]
