# Generated by Django 3.0 on 2025-11-19 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20251111_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell_stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.IntegerField()),
                ('BUYSTOCK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Buy_stock')),
            ],
        ),
    ]
