# Generated by Django 3.0 on 2025-11-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_customer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy_stock',
            name='date',
            field=models.DateField(default='2025-11-22'),
        ),
        migrations.AddField(
            model_name='sell_stock',
            name='date',
            field=models.DateField(default='2025-11-22'),
        ),
    ]
