# Generated by Django 3.0 on 2025-12-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20251129_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy_stock',
            name='total_amount',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='sell_stock',
            name='total_amount',
            field=models.IntegerField(default='0'),
        ),
    ]
