# Generated by Django 3.0 on 2025-12-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20251216_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy_stock',
            name='purchase_price',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='sell_stock',
            name='sell_price',
            field=models.IntegerField(default='0'),
        ),
    ]
