# Generated by Django 3.0 on 2025-12-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20251216_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_stock',
            name='purchase_price',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='buy_stock',
            name='total_amount',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='sell_stock',
            name='sell_price',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='sell_stock',
            name='total_amount',
            field=models.FloatField(default='0'),
        ),
    ]
